### get all users
GET {{BASE_URL}}/user
Authorization: Bearer {{$global.accessToken}}

### get user by id
GET {{BASE_URL}}/user/1
Authorization: Bearer {{$global.accessToken}}

### create user
POST {{BASE_URL}}/user
Content-Type: application/json
{
  "email":"codex@gmail.com",
  "name":"Pojok Code",
  "password":"Pass123"
}

### update user
PUT {{BASE_URL}}/user/7
Content-Type: application/json
{
  "email":"code@gmail.com",
  "name":"Pojok Code",
  "password":"Pass123"
}

### delete user
DELETE {{BASE_URL}}/user/2

### user login
POST {{BASE_URL}}/user/login
Content-Type: application/json
{
  "email":"code@gmail.com",
  "password":"Pass123"
}

{{
  $global.accessToken=JSON.parse(response.body).token;
}}